### ISSUE TITLE
License for repository

### ISSUE THREAD

**Issue by ukBaz** [OpenPiRobotics/CVzero#10]
Currently this repository has no license attributed to it. While there is no obligation to choose a license, without a license, the default copyright laws apply. This means that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. I don't think that is the goal of this repository.

I noticed Tom had put ASL2.0 in setup.py in his PR (which hasn't been merged). 
It is not one of the abbreviations mentions at: https://help.github.com/en/articles/licensing-a-repository
Looking at: https://choosealicense.com/licenses/
Is it Apache License 2.0?

My preference would be to go for the MIT License which is a short and simple permissive license.

The main thing is that a `LICENSE` file is added. If you were to go with the MIT License the text is available from:
https://choosealicense.com/licenses/mit/

If there is agreement on the license to use, I am happy to do a PR

**Comment by flynncowell** [comment]
The project is Open Source. So whatever one covers that, but ultimately it is @Corteil's decision.

**Comment by Corteil** [comment]
I will take a look at this when I get home from my holiday at the weekend

**Comment by tomoinn** [comment]
I've found most libraries use the Apache License (I probably don't have the correct short code!). It's not super critical - just make sure the license is present, and that any references to it (setup.py, and docs) are consistent.

**Comment by Corteil** [comment]
I chose the Mit license, and have updated the files, where required. 
where do I place the license file?

**Comment by ukBaz** [comment]
The `LICENSE` file should be in the top level of the repository.
https://help.github.com/en/articles/adding-a-license-to-a-repository

**Comment by Corteil** [comment]
thanks done
