### ISSUE TITLE
Suggestion: Wrap all imshow with big image resizer

### ISSUE THREAD

**Issue by slowrunner** [OpenPiRobotics/CVzero#21]
I am guessing that most functionality is targeted for 320x240 or 640x480 images, but may be useful on larger images and frames as well.  cv2.imshow() is very not user-friendly for larger images, especially if viewing the Pi Desktop via noVNC which does not allow window resizing.

It would be really great if you wrapped all cv2.imshow() with a utility func that used imshow() for image.shape less than 480,640 and resized by 50% if larger.

**Comment by VishalDhayalan** [comment]
CV Zero monitor only shows stream from Pi camera (set to 640x480) for training from the stream. Functionality for directly adding pictures of objects to learn colour from can be added...

K-means and other algorithms used in the process of learning the colours only show the colour distribution in a window of set size and the HSV range for object tracking. So imshow is only ever used to display the stream from pi camera (which is always set to 640x480), so a utility wrapper for imshow wouldn't be needed right?

**Comment by slowrunner** [comment]
> CV Zero monitor only shows stream from Pi camera (set to 640x480) 
> 
>... imshow is only ever used to display the stream from pi camera (which is always set to 640x480), so a utility wrapper for imshow wouldn't be needed right?

Ok - will close issue
